### ISSUE TITLE
How to install plugin

### ISSUE THREAD

**Issue by bryanyuchen** [jritsema/freeboard-handlebars#2]
How do I install this plugin on freeboard.io?

I've tried copying this link directly into the 'developer console' section, but nothing happens:

https://raw.githubusercontent.com/jritsema/freeboard-handlebars/master/index.js

what do I do?

Thanks

**Comment by jritsema** [comment]
Hi @bryanyuchen.  I added some installation instructions.  Hopefully that helps.

https://github.com/jritsema/freeboard-handlebars#installation

**Comment by bryanyuchen** [comment]
Thanks for the reply @jritsema! However, I was referring to freeboard.io
http://freeboard.io/
I don't think you can edit the project files directly the way you are describing?

**Comment by jritsema** [comment]
Ya, so this assumes you're hosting your own freeboard server.  And yes, you can simply copy the .js file into the freeboard installation and it will work.  Unfortunately, I wasn't able to get my plugins into the official repo to be "in the box".  See [this issue](https://github.com/jritsema/freeboard-jqplot/issues/5) for more info.
